# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgAbout.resize(500, 300)
        dlgAbout.setMinimumSize(QtCore.QSize(500, 300))
        dlgAbout.setMaximumSize(QtCore.QSize(500, 300))
        dlgAbout.setModal(True)
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(180, 30, 121, 81))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\templates\\../img/logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnCloseabout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseabout.setGeometry(QtCore.QRect(200, 230, 80, 25))
        self.btnCloseabout.setMinimumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setMaximumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setObjectName("btnCloseabout")
        self.lblVersion = QtWidgets.QLabel(parent=dlgAbout)
        self.lblVersion.setGeometry(QtCore.QRect(170, 130, 150, 25))
        self.lblVersion.setMinimumSize(QtCore.QSize(150, 25))
        self.lblVersion.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblVersion.setWordWrap(True)
        self.lblVersion.setObjectName("lblVersion")
        self.lblVersion_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.lblVersion_2.setGeometry(QtCore.QRect(110, 180, 250, 25))
        self.lblVersion_2.setMinimumSize(QtCore.QSize(250, 25))
        self.lblVersion_2.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion_2.setFont(font)
        self.lblVersion_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblVersion_2.setWordWrap(True)
        self.lblVersion_2.setObjectName("lblVersion_2")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "About "))
        self.btnCloseabout.setText(_translate("dlgAbout", "Close"))
        self.lblVersion.setText(_translate("dlgAbout", "Version 0.0.1"))
        self.lblVersion_2.setText(_translate("dlgAbout", "Autor: Antón Rubiñán Rodríguez  ©"))
