# Form implementation generated from reading ui file 'C:\Users\jcarl\PycharmProjects\perezgonzalez2526/templates/dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(400, 300)
        dlgCalendar.setMinimumSize(QtCore.QSize(400, 300))
        dlgCalendar.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\jcarl\\PycharmProjects\\perezgonzalez2526/templates\\../img/calendario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgCalendar.setWindowIcon(icon)
        dlgCalendar.setModal(True)
        self.Calendar = QtWidgets.QCalendarWidget(parent=dlgCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.Calendar.setMinimumSize(QtCore.QSize(400, 300))
        self.Calendar.setMaximumSize(QtCore.QSize(400, 300))
        self.Calendar.setSelectedDate(QtCore.QDate(2025, 9, 18))
        self.Calendar.setGridVisible(True)
        self.Calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Calendar"))
